[package]
name = "prt"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
dotenv = "0.15.0"
octocrab = "0.40.0"
ratatui = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full"] }
toml = "0.8.19"
